// Note: This file is generated by the build.gradle script. DO NOT EDIT.
package com.friendlycaptcha.jvm.sdk;

public final class Version {
    public static final String SDK_VERSION = "0.1.0";
    public static final String SDK_NAME = "friendly-captcha-jvm";
    public static final String SDK_IDENTIFIER = "friendly-captcha-jvm@0.1.0";
}
